# Generated by Django 3.1.8 on 2021-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210503_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='HKID',
            field=models.CharField(help_text='Enter Identity Document Number of the case (e.g. A123456(7) )', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.IntegerField(default=0, help_text='Unique ID of the case', unique=True),
        ),
    ]
