# Generated by Django 3.1.8 on 2021-05-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210503_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['location', 'date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
    ]
