# Generated by Django 3.1.8 on 2021-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210503_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Enter name of the location', max_length=1000, null=True),
        ),
    ]
