# Generated by Django 3.1.8 on 2021-05-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210503_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['venue_location']},
        ),
    ]
