# Generated by Django 3.1.8 on 2021-05-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210504_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text='Enter the address', max_length=200, null=True),
        ),
    ]
