# Generated by Django 3.1.8 on 2021-05-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210507_1230'),
        ('catalog', '0011_auto_20210507_0232'),
    ]

    operations = [
    ]
