# Generated by Django 3.1.8 on 2021-05-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0, help_text='Unique ID of the case')),
                ('HKID', models.CharField(help_text='Enter HKID of the case (e.g. A123456(7) )', max_length=10, null=True)),
                ('name', models.CharField(help_text='Enter name of the patient (e.g. Chan Tai Man)', max_length=100, null=True)),
                ('date_of_onset', models.DateField(help_text='Enter the date of onset of the patient', null=True)),
                ('date_of_confirmed', models.DateField(help_text='Enter the date of positive confirmation of the patient', null=True)),
            ],
            options={
                'ordering': ['case_id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enter name of the event', max_length=200, null=True)),
                ('date', models.DateField(help_text='Date of the event', null=True)),
            ],
            options={
                'ordering': ['event_name', 'location', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the location', max_length=200, null=True)),
                ('x_coordination', models.FloatField(help_text='Enter X cordinate of the location', null=True)),
                ('y_coordination', models.FloatField(help_text='Enter Y cordinate of the location', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.event')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location'),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'possible infector'), ('b', 'possibly infected'), ('c', 'both'), ('d', 'none')], default='d', help_text="Patient's role in event", max_length=1)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.case')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.event')),
            ],
            options={
                'ordering': ['case', 'event', 'status'],
            },
        ),
    ]
